version: '3.8'
services:
  backend:
    image: ${BACKEND_IMAGE} # github actions 会自动替换为实际的镜像地址
    env_file:
      - .env
      - .env.production
    ports:
      - "5000:5000"
    restart: always

  frontend:
    image: ${FRONTEND_IMAGE} # github actions 会自动替换为实际的镜像地址
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    restart: always
