services:
  backend:
    build:
      context: ./backend
    container_name: cp-backend-dev
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: ["flask", "run", "--host=0.0.0.0", "--port=5001", "--debug"]
    restart: "no"
    networks:
      - cpkol-net

  frontend:
    build:
      context: ./frontend
      target: development
    container_name: cp-frontend-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - cpkol-net

networks:
  cpkol-net:
    external: true