services:
  backend:
    image: ${BACKEND_IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - ./.env

  frontend:
    image: ${FRONTEND_IMAGE_TAG}
    restart: unless-stopped
    env_file:
      - ./.env 