"""增加updated_date, content_type两列,设置新增和更新记录自动更新updated_date

Revision ID: 5da424e0ade2
Revises: 
Create Date: 2025-06-10 18:21:59.561061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da424e0ade2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('influencer_back_up')
    op.add_column('influencer', sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.execute("UPDATE influencer SET updated_date = NOW()")
    op.add_column('influencer', sa.Column('content_type', sa.String(length=64), nullable=True))
    op.execute("UPDATE influencer SET updated_date = NOW(), content_type = 'normal'")
    op.alter_column('influencer', 'updated_date', nullable=False)
    op.alter_column('influencer', 'content_type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('influencer', 'content_type')
    op.drop_column('influencer', 'updated_date')
    op.create_table('influencer_back_up',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('handle', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sec_uid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('follower_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_play_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_comment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_digg_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('videos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('influencer_copy1_pkey')),
    sa.UniqueConstraint('handle', name=op.f('influencer_copy1_handle_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
