"""add note column

Revision ID: 2a51b0769f85
Revises: b9e9320dc6f0
Create Date: 2025-07-07 15:26:16.793706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a51b0769f85'
down_revision = 'b9e9320dc6f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.drop_column('note')

    # ### end Alembic commands ###
