"""init

Revision ID: 9c306af246bd
Revises: 
Create Date: 2025-07-08 10:53:52.795688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c306af246bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('sec_uid', sa.String(length=256), nullable=True),
    sa.Column('follower_count', sa.Integer(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('total_play_count', sa.Integer(), nullable=True),
    sa.Column('total_comment_count', sa.Integer(), nullable=True),
    sa.Column('total_digg_count', sa.Integer(), nullable=True),
    sa.Column('videos', sa.Text(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=True),
    sa.Column('note', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('digg_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('influencer')
    # ### end Alembic commands ###
