"""init

Revision ID: b9e9320dc6f0
Revises: 
Create Date: 2025-07-07 03:29:28.673096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9e9320dc6f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('desc', sa.String(), nullable=True),
    sa.Column('author_id', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=True),
    sa.Column('digg_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('influencer_back_up')
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('influencer', schema=None) as batch_op:
        batch_op.alter_column('content_type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('updated_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.create_table('influencer_back_up',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('handle', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('sec_uid', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('follower_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_play_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_comment_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_digg_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('videos', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('influencer_copy1_pkey')),
    sa.UniqueConstraint('handle', name=op.f('influencer_copy1_handle_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('videos')
    # ### end Alembic commands ###
